<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-01T16:16:27 IST" name="Suite" finished-at="2025-04-01T16:16:32 IST" duration-ms="5505">
    <groups>
    </groups>
    <test started-at="2025-04-01T16:16:27 IST" name="Test" finished-at="2025-04-01T16:16:32 IST" duration-ms="5505">
      <class name="TestCases.SimpleTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCases.SimpleTest@5af5def9]" started-at="2025-04-01T16:16:27 IST" name="setUp" finished-at="2025-04-01T16:16:32 IST" duration-ms="5104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="secondTest()[pri:2, instance:TestCases.SimpleTest@5af5def9]" started-at="2025-04-01T16:16:32 IST" name="secondTest" finished-at="2025-04-01T16:16:32 IST" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTest -->
        <test-method signature="firstTest()[pri:1, instance:TestCases.SimpleTest@5af5def9]" started-at="2025-04-01T16:16:32 IST" name="firstTest" finished-at="2025-04-01T16:16:32 IST" duration-ms="55" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebDriver.get(String)" because "TestCases.SimpleTest.driver" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.get(String)" because "TestCases.SimpleTest.driver" is null
at TestCases.SimpleTest.firstTest(SimpleTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method is-config="true" signature="generateAllureReport()[pri:0, instance:TestCases.SimpleTest@5af5def9]" started-at="2025-04-01T16:16:32 IST" name="generateAllureReport" finished-at="2025-04-01T16:16:32 IST" duration-ms="27" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateAllureReport -->
      </class> <!-- TestCases.SimpleTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
